[workspace]
channels = ["conda-forge"]
name = "Oscar"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.11"
django = ">=5.2.3,<6"

[pypi-dependencies]
ai-edge-litert = ">=1.3.0,<2"